version: '3.6'

services: 
 
  visualizer-fe:
    image: visualizer-fe
    container_name: visualizer-fe
    hostname: visualizer-fe
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8081:80
    networks:
      - visualizer

networks:
  visualizer:
    name: visualizer
    driver: bridge